#!/bin/bash

run() {
  exec=$1
  printf "\x1b[38;5;104m -- ${exec}\x1b[39m\n"
  eval ${exec}
}

say () {
  say=$1
  printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

say "Install rs-server"
run "mkdir -p /opt/RelayBOX/bin"
run "cp rs-server /opt/RelayBOX/bin && chmod +x /opt/RelayBOX/bin/rs-server"

say "Install rs-client"
run "cp rs-input /opt/RelayBOX/bin && chmod +x /opt/RelayBOX/bin/rs-input"
